# Copyright (c) 2025 FoundationVision
# SPDX-License-Identifier: MIT

import os
os.environ['XFORMERS_FORCE_DISABLE_TRITON'] = '1'
import argparse
import torch

from infinity.models.videovae.models.wan_bsq_vae import AutoencoderKLCogVideoX

def video_vae_model(vqgan_ckpt, schedule_mode, codebook_dim, global_args=None, test_mode=True):
    args=argparse.Namespace(
        vqgan_ckpt=vqgan_ckpt, 
        sd_ckpt=None,
        use_frames=None,
        inference_type='video',
        save_prediction=True,
        save_dir='results',
        intermediate_tensor=True,
        save_z=False,
        save_frames=False,
        image_recon4video=False,
        junke_old=False,
        cal_norm=False,
        save_samples=None,
        device='cuda',
        noise_scale=0.0,
        max_steps=1000000.0,
        log_every=1,
        ckpt_every=1000,
        default_root_dir='/tmp',
        compile='no',
        ema='no',
        mfu_logging='no',
        dataloader_init_epoch=-1,
        context_parallel_size=0,
        video_ranks_ratio=-1.0,
        lr=0.0001,
        beta1=0.9,
        beta2=0.95,
        optim_type='Adam',
        disc_optim_type=None,
        max_grad_norm=1.0,
        max_grad_norm_disc=1.0,
        disable_sch=False,
        scheduler='no',
        warmup_steps=0,
        lr_min=0.0,
        warmup_lr_init=0.0,
        patch_size=8,
        temporal_patch_size=4,
        embedding_dim=256,
        codebook_dim=16,
        use_vae=True,
        eq_scale_prior=0.0,
        eq_angle_prior=0.0,
        use_stochastic_depth=False,
        drop_rate=0.0,
        schedule_mode=schedule_mode,
        lr_drop=None,
        lr_drop_rate=0.1,
        keep_first_quant=False,
        keep_last_quant=False,
        remove_residual_detach=False,
        use_out_phi=False,
        use_out_phi_res=False,
        use_lecam_reg=False,
        lecam_weight=0.05,
        perceptual_model='vgg16',
        base_ch_disc=64,
        random_flip=False,
        flip_prob=0.5,
        flip_mode='stochastic',
        max_flip_lvl=1,
        not_load_optimizer=False,
        use_lecam_reg_zero=False,
        freeze_encoder=False,
        rm_downsample=False,
        random_flip_1lvl=False,
        flip_lvl_idx=0,
        drop_when_test=False,
        drop_lvl_idx=None,
        drop_lvl_num=0,
        compute_all_commitment=False,
        disable_codebook_usage=False,
        freeze_enc_main=False,
        freeze_dec_main=False,
        random_short_schedule=False,
        short_schedule_prob=0.5,
        use_bernoulli=False,
        use_rot_trick=False,
        disable_flip_prob=0.0,
        dino_disc=False,
        quantizer_type='MultiScaleBSQTP',
        lfq_weight=0.0,
        entropy_loss_weight=0.1,
        visu_every=1000,
        commitment_loss_weight=0.25,
        bsq_version='v1',
        diversity_gamma=1,
        bs1_for1024=False,
        casual_multi_scale=False,
        double_compress_t=False,
        temporal_slicing=False,
        latent_adjust_type=None,
        compute_latent_loss=False,
        latent_loss_weight=0.0,
        use_raw_latentz=False,
        last_scale_repeat_n=0,
        num_lvl_fsq=5,
        use_midscale_sup=False,
        midscale_list=[0.5, 0.75, 1.0],
        use_eq=False,
        eq_prob=0.5,
        disc_version='v1',
        magvit_disc=False,
        disc_type='patchgan',
        sigmoid_in_disc=False,
        activation_in_disc='leaky_relu',
        apply_blur=False,
        apply_noise=False,
        dis_warmup_steps=0,
        dis_lr_multiplier=1.0,
        dis_minlr_multiplier=False,
        disc_channels=64,
        disc_layers=3,
        discriminator_iter_start=0,
        disc_pretrain_iter=0,
        disc_optim_steps=1,
        disc_warmup=0,
        disc_pool='no',
        disc_pool_size=100,
        disc_temporal_compress='yes',
        disc_use_blur='yes',
        disc_stylegan_downsample_base=2,
        fix_model=['no'],
        recon_loss_type='l1',
        image_gan_weight=1.0,
        video_gan_weight=1.0,
        image_disc_weight=0.0,
        video_disc_weight=0.0,
        vf_weight=0.0,
        vf_weight_approx=-1,
        vf_distmat_margin=0.25,
        vf_cos_margin=0.5,
        temporal_alignment=None,
        l1_weight=4.0,
        gan_feat_weight=0.0,
        lpips_model='vgg',
        perceptual_weight=0.0,
        video_perceptual_weight=None,
        video_perceptual_layers=[],
        kl_weight=0.0,
        norm_type='rms',
        disc_loss_type='hinge',
        gan_image4video='yes',
        use_checkpoint=False,
        precision='fp32',
        encoder_dtype='fp32',
        decoder_dtype='fp32',
        upcast_attention='',
        upcast_tf32=False,
        tokenizer='cogvideoxd',
        pretrained=None,
        pretrained_mode='full',
        pretrained_ema='no',
        inflation_pe=False,
        init_vgen='no',
        no_init_idis=False,
        init_idis='keep',
        init_vdis='no',
        enable_nan_detector=False,
        turn_on_profiler=False,
        profiler_scheduler_wait_steps=10,
        debug=False,
        video_logger=False,
        bytenas='sg',
        username='bin.yan',
        seed=1234,
        vq_to_vae=False,
        load_not_strict=False,
        zero=0,
        bucket_cap_mb=40,
        manual_gc_interval=10000,
        data_path=[''],
        data_type=[''],
        dataset_list=['wanxvideo-v1'],
        fps=[-1],
        dataaug='resizecrop',
        multi_resolution=False,
        random_bucket_ratio=0.0,
        sequence_length=81,
        resolution=[(480, 864)],
        resize_bucket=None,
        resize_bucket_use_self='yes',
        scaling_aug='no',
        batch_size=[1],
        num_workers=0,
        image_channels=3,
        in_channels=3,
        out_channels=3,
        down_block_types=['CogVideoXDownBlock3D',
        'CogVideoXDownBlock3D',
        'CogVideoXDownBlock3D',
        'CogVideoXDownBlock3D'],
        down_block_mode='dc',
        up_block_types=['CogVideoXUpBlock3D',
        'CogVideoXUpBlock3D',
        'CogVideoXUpBlock3D',
        'CogVideoXUpBlock3D'],
        up_block_mode='dc',
        block_out_channels=[96, 192, 384, 384, 384],
        layers_per_block=2,
        latent_channels=16,
        act_fn='silu',
        norm_eps=1e-06,
        norm_num_groups=32,
        spatial_compression_list=[2, 2, 2],
        temporal_compression_list=[2, 2],
        sample_height=480,
        sample_width=720,
        use_quant_conv=False,
        use_post_quant_conv=False,
        down_layer='3d-dc',
        down_norm=True,
        up_layer='3d-dc',
        up_norm=True,
        pad_mode='constant',
        dropout_z=0.0,
        flux_weight=0,
        cycle_weight=0,
        cycle_feat_weight=0,
        cycle_gan_weight=0,
        cycle_loop=0,
        cycle_norm='no',
        cycle_deterministic='no',
        cycle_kl_weight=0,
        z_drop=0.0,
        intermediate_tensor_dir='/tmp',
        codebook_dim_low=codebook_dim//4,
        freeze_decoder=False,
        semantic_scale_dim=global_args.semantic_scale_dim,
        detail_scale_dim=global_args.detail_scale_dim,
        use_learnable_dim_proj=global_args.use_learnable_dim_proj,
        detail_scale_min_tokens=global_args.detail_scale_min_tokens,
        use_feat_proj=global_args.use_feat_proj,
        semantic_scales=global_args.semantic_scales,
        use_multi_scale=0,
        quant_not_rely_256=0,
        semantic_num_lvl=2,
        detail_num_lvl=2,
    )

    vae = AutoencoderKLCogVideoX(args)
    state_dict = torch.load(args.vqgan_ckpt, map_location=torch.device("cpu"), weights_only=True)
    if args.ema == "yes":
        print("testing ema weights")
        vae.load_state_dict(state_dict["ema"], strict=False)
    else:
        vae.load_state_dict(state_dict["vae"], strict=False)

    vae.enable_slicing()
    if test_mode:
        vae.eval()
        [p.requires_grad_(False) for p in vae.parameters()]
    return vae